
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/projectDatabase
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data: